version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.67.2:32555 # Corrigé avec le bon port du service OpenFaaS Gateway
  namespace: openfaas-fn
functions:
  create-account:
    lang: python3-flask # Utilisation du template Flask
    handler: ./create-account 
    image: jersauret/create-account:latest 
    environment:
      DB_HOST: postgresql.database.svc.cluster.local
      DB_NAME: your_database_name
      DB_USER: "user"
      DB_PASSWORD: "votreMotDePasseFort"
      ENCRYPTION_KEY: "qndx3Dv5HwpBO1CYytW7SNQe19qjMDJvN2nXMB9Dhaw="
  authenticate-user:
    lang: python3-flask
    handler: ./authenticate-user
    image: jersauret/authenticate-user:latest
    environment:
      DB_HOST: postgresql.database.svc.cluster.local
      DB_NAME: your_database_name
      DB_USER: "user"
      DB_PASSWORD: "votreMotDePasseFort"
      ENCRYPTION_KEY: "qndx3Dv5HwpBO1CYytW7SNQe19qjMDJvN2nXMB9Dhaw="
